#!/bin/bash

CC=gcc
CXX=g++
CFLAGS= -std=c++11
LIBS= -lpthread

all: server

server: ./obj/main.o ./obj/ClientInfo.o
	$(CXX) $(CFLAGS) ./obj/main.o ./obj/ClientInfo.o $(LIBS) -o server 

./obj/main.o: ./src/main.cpp ./inc/ClientInfo.h
	$(CXX) $(CFLAGS) -c -I"./inc" ./src/main.cpp $(LIBS) -o ./obj/main.o

./obj/ClientInfo.o: ./src/ClientInfo.cpp ./inc/ClientInfo.h
	$(CXX) $(CFLAGS) -c -I"./inc" ./src/ClientInfo.cpp -o ./obj/ClientInfo.o

clean:
	rm -rf ./obj/*.o server
